# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [ 19,27,  44,40,  38,94 ]  # P3/8
  - [ 96,68,  86,152,  180,137 ]  # P4/16
  - [ 140,301,  303,264,  238,542 ]  # P5/32
  - [ 436,615,  739,380,  925,792 ]  # P6/64

# yolov7-e6e backbone
backbone:
  # [from, number, module, args],     
  [[-1, 1, ReOrg, []],                                  # (0)
   [-1, 1, Conv, [80, 3, 1]],                           # (1)
   
   [-1, 1, DownC, [160]],                               # 2
   [-1, 1, BBConvBlock, [64, 160]],                     # 3
   [-2, 1, BBConvBlock, [64, 160]],                     # 4
   [[-1, -2], 1, Shortcut, [1]],                        # 5(23)

   [-1, 1, DownC, [320]],                               # 6
   [-1, 1, BBConvBlock, [128,320]],                     # 7
   [-2, 1, BBConvBlock, [128,320]],                     # 8
   [[-1, -2], 1, Shortcut, [1]],                        # 9(45)

   [-1, 1, DownC, [640]],                               # 10
   [-1, 1, BBConvBlock, [256, 640]],                    # 11
   [-2, 1, BBConvBlock, [256, 640]],                    # 12
   [[-1, -2], 1, Shortcut, [1]],                        # 13(67)

   [-1, 1, DownC, [960]],                               # 14
   [-1, 1, BBConvBlock, [384, 960]],                    # 15
   [-2, 1, BBConvBlock, [384, 960]],                    # 16
   [[-1, -2], 1, Shortcut, [1]],                        # 17(89)

   [-1, 1, DownC, [1280]],                              # 18
   [-1, 1, BBConvBlock, [512, 1280]],                   # 19
   [-2, 1, BBConvBlock, [512, 1280]],                   # 20
   [[-1, -2], 1, Shortcut, [1]],                        # 21(111)
  ]

# yolov7-e6e head
head:
  [
   #Decoder1: (89),(67),(45) => x3
  #  [-1, 1, SkipDeconvBlock, [512, 1280, True]],         # 22
  #  [-1, 1, DeconvDownC, [960]],                         # 23[17(89)]
  #  [-1, 1, SkipDeconvBlock, [384, 960, True]],          # 24
  #  [-1, 1, DeconvDownC, [640]],                         # 25[13(67)]
  #  [-1, 1, SkipDeconvBlock, [256, 640, True]],          # 26
  #  [-1, 1, DeconvDownC, [320]],                         # 27[9(45)] //+6

   [-1, 1, SPPCSPC, [640]],                             # 22(112)

   [-1, 1, Conv, [480, 1, 1]],                          # 23(113)
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],          # 24(114)
   [17, 1, Conv, [480, 1, 1]],                          # 25(115)->17(89)
   [[-1, -2], 1, Concat, [1]],                          # 26(116)
   [-1, 1, HConvBlock, [192, 480]],                     # 27
   [-2, 1, HConvBlock, [192, 480]],                     # 28
   [[-1, -2], 1, Shortcut, [1]],                        # 29(137)
  
   [-1, 1, Conv, [320, 1, 1]],                          # 30(138)
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],          # 31(139)
   [13, 1, Conv, [320, 1, 1]],                          # 32(140)->13(67)
   [[-1, -2], 1, Concat, [1]],                          # 33(141)
   [-1, 1, HConvBlock, [128, 320]],                     # 34
   [-2, 1, HConvBlock, [128, 320]],                     # 35
   [[-1, -2], 1, Shortcut, [1]],                        # 36(162)

   [-1, 1, Conv, [160, 1, 1]],                          # 37(163)
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],          # 38(164)
   [9, 1, Conv, [160, 1, 1]],                           # 39(165)->9(45)
   [[-1, -2], 1, Concat, [1]],                          # 40(166)
   [-1, 1, HConvBlock, [64, 160]],                      # 41
   [-2, 1, HConvBlock, [64, 160]],                      # 42
   [[-1, -2], 1, Shortcut, [1]],                        # 43(187)

   #Decoder2: 36(162),29(137),22(112) => x3
   [-1, 1, HDeconvBlock_T, [64, 320]],                  # 44
   [-1, 1, nn.MaxPool2d, [2, 2]],                       # 45
   [-1, 1, DeConv, [320, 1, 1]],                        # 46[36(162)]
   [-1, 1, HDeconvBlock_T, [128, 640]],                 # 47
   [-1, 1, nn.MaxPool2d, [2, 2]],                       # 48
   [-1, 1, DeConv, [480, 1, 1]],                        # 49[29(137)]
   [-1, 1, HDeconvBlock_T, [192, 960]],                 # 50
   [-1, 1, nn.MaxPool2d, [2, 2]],                       # 51
   [-1, 1, DeConv, [640, 1, 1]],                        # 52[22(112)] //+9

   [43, 1, DownC, [320]],                               # 44(188)
   [[-1, 46], 1, Concat, [1]],                          # 45(189)->36(162)
   [-1, 1, HConvBlock, [128, 320]],                     # 46
   [-2, 1, HConvBlock, [128, 320]],                     # 47
   [[-1, -2], 1, Shortcut, [1]],                        # 48(210)

   [-1, 1, DownC, [480]],                               # 49(211)
   [[-1, 49], 1, Concat, [1]],                          # 50(212)->29(137)
   [-1, 1, HConvBlock, [192, 480]],                     # 51
   [-2, 1, HConvBlock, [192, 480]],                     # 52
   [[-1, -2], 1, Shortcut, [1]],                        # 53(233)

   [-1, 1, DownC, [640]],                               # 54(234)
   [[-1, 52], 1, Concat, [1]],                          # 55(235)->22(112)
   [-1, 1, HConvBlock, [256, 640]],                     # 56
   [-2, 1, HConvBlock, [256, 640]],                     # 57
   [[-1, -2], 1, Shortcut, [1]],                        # 58(256)

   #Decoder3: (187),(210),(233),(256) => x3
  #  [-1, 1, SkipDeconvBlock, [256, 640, False]],         # 22
  #  [-1, 1, DeconvDownC, [480]],                         # 23[17(89)]
  #  [-1, 1, SkipDeconvBlock, [192, 480, False]],         # 22
  #  [-1, 1, DeconvDownC, [320]],                         # 29[13(67)]
  #  [-1, 1, SkipDeconvBlock, [128, 320, False]],         # 22
  #  [-1, 1, DeconvDownC, [160]],                         # 33[9(45)] //+6

   [43, 1, Conv, [320, 3, 1]],                          # 59(257)->43(187)
   [57, 1, Conv, [640, 3, 1]],                          # 60(258)->48(210)
   [62, 1, Conv, [960, 3, 1]],                          # 61(259)->53(233)
   [67, 1, Conv, [1280, 3, 1]],                         # 62(260)->58(256)

   [[68,69,70,71], 1, Detect, [nc, anchors]],           # 63(261)
  ]
