  # parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [ 19,27,  44,40,  38,94 ]  # P3/8
  - [ 96,68,  86,152,  180,137 ]  # P4/16
  - [ 140,301,  303,264,  238,542 ]  # P5/32
  - [ 436,615,  739,380,  925,792 ]  # P6/64

# yolov7-e6e backbone
backbone:
  # [from, number, module, args],     
  [
   [-1, 1, DownC, [640]],                               # 0
   [-1, 1, BBConvBlock, [256, 640]],                    # 1
   [-2, 1, BBConvBlock, [256, 640]],                    # 2
   [[-1, -2], 1, Shortcut, [1]],                        # 3(67)

   [-1, 1, DownC, [960]],                               # 4
   [-1, 1, BBConvBlock, [384, 960]],                    # 5
   [-2, 1, BBConvBlock, [384, 960]],                    # 6
   [[-1, -2], 1, Shortcut, [1]],                        # 7(89)

   [-1, 1, DownC, [1280]],                              # 8
   [-1, 1, BBConvBlock, [512, 1280]],                   # 9
   [-2, 1, BBConvBlock, [512, 1280]],                   # 10
   [[-1, -2], 1, Shortcut, [1]],                        # 11(111)
  ]

# yolov7-e6e head
head:
  [
  #Decoder1: (89),(67),(45) => x3

   [-1, 1, SPPCSPC, [640]],                             # 12(112)

   [-1, 1, Conv, [480, 1, 1]],                          # 13(113)
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],          # 14(114)
   [7, 1, Conv, [480, 1, 1]],                           # 15(115)->7(89)
   [[-1, -2], 1, Concat, [1]],                          # 16(116)
   [-1, 1, HConvBlock, [192, 480]],                     # 17
   [-2, 1, HConvBlock, [192, 480]],                     # 18
   [[-1, -2], 1, Shortcut, [1]],                        # 19(137)

   [-1, 1, Conv, [320, 1, 1]],                          # 20(138)
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],          # 21(139)
   [3, 1, Conv, [320, 1, 1]],                           # 22(140)->3(67)
   [[-1, -2], 1, Concat, [1]],                          # 23(141)
   [-1, 1, HConvBlock, [128, 320]],                     # 24
   [-2, 1, HConvBlock, [128, 320]],                     # 25
   [[-1, -2], 1, Shortcut, [1]],                        # 26(162)

   [-1, 1, Conv, [160, 1, 1]],                          # 27(163)
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],          # 28(164)
   [0, 1, Conv, [160, 1, 1]],                           # 29(165)->0(45)
   [[-1, -2], 1, Concat, [1]],                          # 30(166)
   [-1, 1, HConvBlock, [64, 160]],                      # 31
   [-2, 1, HConvBlock, [64, 160]],                      # 32
   [[-1, -2], 1, Shortcut, [1]],                        # 33(187)

  #Decoder2: 36(162),29(137),22(112) => x3

   [-1, 1, DownC, [320]],                               # 34(188)
   [[-1, 26], 1, Concat, [1]],                          # 35(189)->26(162)
   [-1, 1, HConvBlock, [128, 320]],                     # 36
   [-2, 1, HConvBlock, [128, 320]],                     # 37
   [[-1, -2], 1, Shortcut, [1]],                        # 38(210)

   [-1, 1, DownC, [480]],                               # 39(211)
   [[-1, 19], 1, Concat, [1]],                          # 40(212)->19(137)
   [-1, 1, HConvBlock, [192, 480]],                     # 41
   [-2, 1, HConvBlock, [192, 480]],                     # 42
   [[-1, -2], 1, Shortcut, [1]],                        # 43(233)

   [-1, 1, DownC, [640]],                               # 44(234)
   [[-1, 12], 1, Concat, [1]],                          # 45(235)->12(112)
   [-1, 1, HConvBlock, [256, 640]],                     # 46
   [-2, 1, HConvBlock, [256, 640]],                     # 47
   [[-1, -2], 1, Shortcut, [1]],                        # 48(256)

  # Decoder3: #43(187),48(210),53(233),58(256) => x3
  ]


Decoder:
  [
    # Decoder1: #17(89),13(67),9(45) => x3:
    [
      [-1, 1, SkipDeconvBlock, [512, 1280, True]],         # 22
      [-1, 1, DeconvDownC, [960]],                         # 23[17(89)]
      [7, 1, SkipDeconvBlock, [384, 960, True]],           # 22
      [-1, 1, DeconvDownC, [640]],                         # 29[13(67)]
      [3, 1, SkipDeconvBlock, [256, 640, True]],           # 22
      [-1, 1, DeconvDownC, [320]],                         # 33[9(45)] //+6
    ],
    # Decoder2: #36(162),29(137),22(112) => x3
    [
      [-1, 1, SkipDeconvBlock, [64, 160, False]],          # 22
      [-1, 1, nn.MaxPool2d, [2, 2]],                       # 47
      [-1, 1, DeConv, [320, 1, 1]],                        # 48[36(162)]
      [26, 1, SkipDeconvBlock, [128, 320, False]],         # 22
      [-1, 1, nn.MaxPool2d, [2, 2]],                       # 47
      [-1, 1, DeConv, [480, 1, 1]],                        # 48[29(137)]
      [19, 1, SkipDeconvBlock, [192, 480, False]],         # 22
      [-1, 1, nn.MaxPool2d, [2, 2]],                       # 47
      [-1, 1, DeConv, [640, 1, 1]],                        # 48[22(112)] //+9
    ],
    # Decoder3: #43(187),48(210),53(233),58(256) => x3
    [
      [-1, 1, SkipDeconvBlock, [256, 640, False]],         # 22
      [-1, 1, DeconvDownC, [480]],                         # 23[17(89)]
      [43, 1, SkipDeconvBlock, [192, 480, False]],         # 22
      [-1, 1, DeconvDownC, [320]],                         # 29[13(67)]
      [38, 1, SkipDeconvBlock, [128, 320, False]],         # 22
      [-1, 1, DeconvDownC, [160]],                         # 33[9(45)] //+6
    ]
  ]